pages:
  stage: deploy
  image: rustlang/rust:nightly
  script:
  - cargo +stable check
  - cargo +nightly check
  - ./test.sh
  - cargo doc
  - cp -r target/doc public
  artifacts:
    paths:
    - public
  only:
  - master
