pages:
  stage: deploy
  script:
  - cargo doc
  - cp -r target/doc public
  artifacts:
    paths:
    - public
  only:
  - master


before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="~/.cargo/bin:$PATH"
  - cargo --version

check:
  script:
  - cargo check
  - cargo test --test-threads=1
