[formatting]
align_entries         = true
array_auto_collapse   = false
column_width          = 40
indent_entries        = false
indent_tables         = false
reorder_arrays        = false
reorder_inline_tables = true
reorder_keys          = true
